### ISSUE TITLE
Verify Higher Order Function

### ISSUE THREAD

**Issue by elsennov** [nhaarman/mockito-kotlin#145]
Hi, let's say i have this function

```
fun determineBottomBarView(assignee: String?,
                               showChatAssignerFunction: () -> Unit,
                               showChatComposerFunction: () -> Unit,
                               hideChatComposerAndAssignerFunction: () -> Unit) {
        if (assignee.isNullOrEmpty()) {
            showChatAssignerFunction()
        } else {
            if (assignee.equals(localRequestManager.getUsername())) {
                showChatComposerFunction()
            } else {
                hideChatComposerAndAssignerFunction()
            }
        }
    }
```

How to verify `showChatAssignerFunction` is called when assignee is null or empty using this library? Is it possible? Thank you!

**Comment by henrikpersson** [comment]
Hi @nhaarman,

Do you know why your example doesn't work while using Robolectric? With Robolectric I get this error:

```
org.mockito.exceptions.base.MockitoException: 
ClassCastException occurred while creating the mockito mock :
  class to mock : 'kotlin.jvm.functions.Function0$MockitoMock$1621993339', loaded by classloader : 'MultipleParentClassLoader{parents=[sun.misc.Launcher$AppClassLoader@7852e922, org.robolectric.internal.bytecode.InstrumentingClassLoader@6536e911]}'
  created class : 'kotlin.jvm.functions.Function0', loaded by classloader : 'sun.misc.Launcher$AppClassLoader@7852e922'
  proxy instance class : 'kotlin.jvm.functions.Function0$MockitoMock$1621993339', loaded by classloader : 'MultipleParentClassLoader{parents=[sun.misc.Launcher$AppClassLoader@7852e922, org.robolectric.internal.bytecode.InstrumentingClassLoader@6536e911]}'
  instance creation by : ObjenesisInstantiator```

**Comment by simon-tse-hs** [comment]
@henrikpersson I also have this problem too. I'd get something like this

```
org.mockito.exceptions.misusing.UnfinishedVerificationException: 
Missing method call for verify(mock) here:
-> at com.nhaarman.mockitokotlin2.VerificationKt.verify(Verification.kt:42)

Example of correct verification:
    verify(mock).doSomething()

Also, this error might show up because you verify either of: final/private/equals()/hashCode() methods.
Those methods *cannot* be stubbed/verified.
Mocking methods declared on non-public parent classes is not supported.


	at org.mockito.internal.junit.JUnitRule$1.evaluate(JUnitRule.java:44)
	at com.hootsuite.testing.rule.RxJavaSchedulerRule$apply$1.evaluate(RxJavaSchedulerRule.kt:31)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:253)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)

```

**Comment by jameswald** [comment]
I was able to rule out mockito-kotlin by reproducing this issue with Robolectric and Mockito: https://github.com/robolectric/robolectric/issues/5076.
