### ISSUE TITLE
Stubbing Fails for Methods with Non-constant Default Parameters

### ISSUE THREAD

**Issue by desilvai** [nhaarman/mockito-kotlin#174]
Kotlin permits defining default parameters for methods that are data members of the class.  However, stubbing such a method then verifying it causes a failure because stubbing will convert the default parameter to a null-value and `verify` assumes the default parameter is non-null.  When the original type of the default parameter is non-null, there is no way for me to verify using a pattern that supports null.

To make it more concrete, I've attached a test case (including build script -- [test.tar.gz](https://github.com/nhaarman/mockito-kotlin/files/1043001/test.tar.gz)) that demonstrates the issue.  Executing this test case, results in 
```
Argument(s) are different! Wanted:
classToMock.printSomething(
    <any java.lang.String>,
    <any java.lang.String>
);
-> at ClassToMock.printSomething(Test.kt:11)
Actual invocation has different arguments:
classToMock.printSomething(
    "TEST",
    null
);
-> at ClassToMock.printSomething$default(Test.kt:10)

	at ClassToMock.printSomething(Test.kt:11)
	at DefaultParameterFail.default parameter will cause verifier failure(Test.kt:29)

```
Here, the stubbed method was `fun printSomething(message: String, suffix: String = defaultValue)`.  Notice that the second parameter (the default parameter) becomes null upon stubbing, so verifying that it was invoked fails.

**Comment by nhaarman** [comment]
For completeness, the simplified code from the test project:

```kotlin
class ClassToMock(val defaultValue: String = "DEFAULT") {

    fun printSomething(message: String, suffix: String = defaultValue) {
        print("$message - $suffix")
    }
}

class DefaultParameterFail {

    @Test
    fun `default parameter will cause verifier failure`() {
        val mockedPrinter = mock<ClassToMock>()
        mockedPrinter.printSomething("1")
        verify(mockedPrinter).printSomething(any(), any())
    }
}
```

**Comment by nhaarman** [comment]
`ClassToMock` gets compiled to the following:

```java
public final class ClassToMock {

   @NotNull
   private final String defaultValue;

   public ClassToMock(@NotNull String defaultValue) {
      Intrinsics.checkParameterIsNotNull(defaultValue, "defaultValue");
      super();
      this.defaultValue = defaultValue;
   }

   // $FF: synthetic method
   public ClassToMock(String var1, int var2, DefaultConstructorMarker var3) {
      if((var2 & 1) != 0) {
         var1 = "DEFAULT";
      }

      this(var1);
   }

   public ClassToMock() {
      this((String)null, 1, (DefaultConstructorMarker)null);
   }

   public final void printSomething(@NotNull String message, @NotNull String suffix) {
      Intrinsics.checkParameterIsNotNull(message, "message");
      Intrinsics.checkParameterIsNotNull(suffix, "suffix");
      String var3 = message + " - " + suffix;
      System.out.print(var3);
   }

   // $FF: synthetic method
   // $FF: bridge method
   public static void printSomething$default(ClassToMock var0, String var1, String var2, int var3, Object var4) {
      if((var3 & 2) != 0) {
         var2 = var0.defaultValue;
      }

      var0.printSomething(var1, var2);
   }

   @NotNull
   public final String getDefaultValue() {
      return this.defaultValue;
   }
}
```

The line `mockedPrinter.printSomething("1")` actually calls the method `printSomething$default` with `null` for `var2`:

```java
public static void printSomething$default(ClassToMock var0, String var1, String var2, int var3, Object var4) {
  if((var3 & 2) != 0) {
     var2 = var0.defaultValue;
  }

  var0.printSomething(var1, var2);
}
```

This static methods calls `printSomething` with the `defaultValue` field of the `ClassToMock` instance for `var2`. However since this instance is a mock, its constructor was never executed and `defaultValue == null`. That is why your assertion fails.

**Comment by nhaarman** [comment]
As an alternative, you can use `anyOrNull()`:

```kotlin
verify(mockedPrinter).printSomething(any(), anyOrNull())
```

**Comment by nhaarman** [comment]
Closing issue due to inactivity

**Comment by danielgomezrico** [comment]
@nhaarman maybe `any()` can check if the type is nullable and then use `anyOrNull()` inside of it based on that?
