### ISSUE TITLE
Mocking a lambda using the `mock {} on { invoke()} doReturn` throws a NullPointerException

### ISSUE THREAD

**Issue by mkobit** [nhaarman/mockito-kotlin#199]
Tested with Kotlin 1.1.4.2 and version 1.5.0 of this library

Example:

```kotlin
@Test
fun `mocking a lambda block`() {
    val function1: () -> Int = mock()
    whenever(function1.invoke())  // 'invokedMethod' -> public abstract java.lang.Object kotlin.jvm.functions.Function0.invoke()
        .thenReturn(1)

    val f1Val = function1.invoke()
    // Succeeds
    assertThat(f1Val).isEqualTo(1)

    val function2: () -> Int = mock {
        // this fails on the 'invoke()'
        on { invoke() } doReturn 2
    }
    val f2Val = function2.invoke()
    assertThat(f2Val).isEqualTo(2)
}
```

Stacktrace:

```
com.nhaarman.mockito_kotlin.MockitoKotlinException: NullPointerException thrown when stubbing. If you are trying to stub a generic method, try `onGeneric` instead.

	at com.nhaarman.mockito_kotlin.KStubbing.on(Mockito.kt:215)
	at MkobitRepro.mocking a lambda block(MkobitRepro.kt:303)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NullPointerException
	at MkobitRepro$mocking a lambda block$function2$1$1.invoke(MkobitRepro.kt:303)
	at MkobitRepro$mocking a lambda block$function2$1$1.invoke(MkobitRepro.kt:26)
	at com.nhaarman.mockito_kotlin.KStubbing.on(Mockito.kt:213)
```

**Comment by nhaarman** [comment]
`() -> Int` resolves to `Function<Int>` which is a generic. For this, `onGeneric` needs to be used. 
The error message should become clearer though. Perhaps `on` and `onGeneric` should be combined into a single method.

```kotlin
val function2: () -> Int = mock {
    onGeneric { invoke() } doReturn 2
}
```

Related: #195

**Comment by mkobit** [comment]
Good catch with the `Function<Int>` - the `onGeneric` reasoning makes sense although I am a little confused as to why the first `whenever` example didn't throw an exception.

**Comment by nhaarman** [comment]
I'm a bit rusty on the internals of Mockito, but the source of the `onGeneric` function explains that an NPE may be thrown when a generic non-nullable type is used:

https://github.com/nhaarman/mockito-kotlin/blob/master/mockito-kotlin/src/main/kotlin/com/nhaarman/mockito_kotlin/Mockito.kt#L197

> why the first whenever example didn't throw an exception

Me too for now :sweat_smile:

**Comment by mkobit** [comment]
Thanks for the explanation, going to close unless you think there is more action needed.
