### ISSUE TITLE
Doesn't work for Android tests

### ISSUE THREAD

**Issue by autonomousapps** [nhaarman/mockito-kotlin#200]
I am using this lib successfully for unit tests, but when I try to use it for an instrumented Android test, I get the following:
Use:
```
import com.nhaarman.mockito_kotlin.mock
val n: AppData = mock()
```
Error:
```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/nhaarman/mockito_kotlin/MockitoKt;
at com.myproject.tests.Test.testSomething(Test.kt:91)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:270)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
at com.jakewharton.u2020.U2020TestRunner.onStart(U2020TestRunner.java:22)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.nhaarman.mockito_kotlin.MockitoKt" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.myproject.test-1/base.apk", zip file "/data/app/com.myproject-2/base.apk"],nativeLibraryDirectories=[/data/app/com.myproject.test-1/lib/x86, /data/app/com.myproject-2/lib/x86, /data/app/com.myproject.test-1/base.apk!/lib/x86, /data/app/com.myproject-2/base.apk!/lib/x86, /system/lib, /vendor/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
... 34 more
```

**Comment by autonomousapps** [comment]
Note: I have a similar issue with the Kluent project, and have filed a sibling issue there: https://github.com/MarkusAmshove/Kluent/issues/66

**Comment by 540Grunkspin** [comment]
Could this maybe be proguard related?

**Comment by autonomousapps** [comment]
No, I don't proguard debug builds.

**Comment by 540Grunkspin** [comment]
I will try tomorrow and see if I can reproduce it. I only have robolectric tests on my current project.

**Comment by malenalbc** [comment]
Maybe this helps, I have been having trouble with android tests too:

```
IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker
at org.mockito.internal.configuration.plugins.PluginLoader$1.invoke(PluginLoader.java:66)
at java.lang.reflect.Proxy.invoke(Proxy.java:397)
at $Proxy4.isTypeMockable(Unknown Source)
at org.mockito.internal.util.MockUtil.typeMockabilityOf(MockUtil.java:29)
at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:186)
at org.mockito.internal.creation.MockSettingsImpl.confirm(MockSettingsImpl.java:180)
at org.mockito.internal.MockitoCore.mock(MockitoCore.java:62)
at org.mockito.Mockito.mock(Mockito.java:1729)
```

```
IMPORTANT INFORMATION FOR ANDROID USERS:

The regular Byte Buddy mock makers cannot generate code on an Android VM!
To resolve this, please use the 'mockito-android' dependency for your application:
http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22mockito-android%22%20g%3A%22org.mockito%22
```

I have it in the test module and works ok, but when adding it to `androidTestCompile` and using it doesn't work.

**Comment by Fondesa** [comment]
For the moment, you can do this workaround:

    androidTestCompile("com.nhaarman:mockito-kotlin-kt1.1:1.5.0", {
        exclude group: 'org.mockito', module: 'mockito-core'
    })
    androidTestCompile "org.mockito:mockito-android:2.11.0"

I hope it will be supported soon, in case, I can submit a PR for it.

**Comment by autonomousapps** [comment]
Thanks, @Fondesa , I will try it.

**Comment by nhaarman** [comment]
Doesn't just adding `mockito-android` as another dependency work?

```
androidTestCompile 'com.nhaarman:mockito-kotlin:x.x.x`
androidTestCompile 'org.mockito:mockito-android:x.x.x`
```

**Comment by Fondesa** [comment]
@nhaarman You are right, it works too.

**Comment by Fondesa** [comment]
The only think that could be useful is to have something like: 
```gradle
androidTestCompile 'com.nhaarman:mockito-kotlin-android:x.x.x`
```

It can be useful to:
- avoid to specify two dependencies
- align the version of the `mockito-android` library with yours

But adding `org.mockito:mockito-android` is ok also.

**Comment by nhaarman** [comment]
We'll avoid adding artifacts just to include extra dependencies.

**Comment by autonomousapps** [comment]
Old issue, and I know I didn't follow up, but I can't find reference to any `org.mockito:mockito-android` artifact anywhere. Where is it hosted? Who owns it?

**Comment by bogdanzurac** [comment]
Am I missing something? This issue is still happening, even with the mockito-android dependency added:

```
    androidTestImplementation("com.nhaarman.mockitokotlin2:mockito-kotlin:2.0.0-RC1", {
        exclude group: 'org.mockito', module: 'mockito-core'
    })
    androidTestImplementation 'org.mockito:mockito-android:2.19.0'
```

Error log:

```
Caused by: org.mockito.exceptions.base.MockitoInitializationException:
Could not initialize inline Byte Buddy mock maker. (This mock maker is not supported on Android.)


IMPORTANT INFORMATION FOR ANDROID USERS:

The regular Byte Buddy mock makers cannot generate code on an Android VM!
To resolve this, please use the 'mockito-android' dependency for your application:
http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22mockito-android%22%20g%3A%22org.mockito%22

Java               : 0.9
JVM vendor name    : The Android Project
JVM vendor version : 2.1.0
JVM name           : Dalvik
JVM version        : 0.9
JVM info           : null
OS name            : Linux
OS version         : 4.4.116-g6999c7c9f794
```

**Comment by wakwak3125** [comment]
@bogdanzurac 
Make sure mockito-core version that used by mockit-kotlin.
2.0.0-RC1 uses 2.21.0.
It should be use same version.

**Comment by hamadycisse** [comment]
Using the same versions for Mockito and Mockito-Kotlin worked for me
