### ISSUE TITLE
kotlin coroutines support

### ISSUE THREAD

**Issue by nf17** [nhaarman/mockito-kotlin#215]
i am getting the below when i try to mock and verify on an activity that's calling a suspend function

**Error:**
Argument(s) are different! Wanted:
userManager.getAccountInfo(
    _(onCreate_callsGetAccountInformation$1) kotlinx.coroutines.experimental.CoroutineScope.() -> kotlin.Unit
);_
-> at com.humana.pharmacy.AccountActivityTests$onCreate_callsGetAccountInformation$1.doResume(AccountActivityTests.kt:117)
Actual invocation has different arguments:
_userManager.getAccountInfo(
    () kotlinx.coroutines.experimental.CoroutineScope.() -> kotlin.Unit
)_
-> at com.humana.pharmacy.AccountActivity$loadAccountInfoAsync$1$1.doResume(AccountActivity.kt:199)

**Code**
I have my unit test case decorated with runBlocking like this:
`@Test
    fun onCreate_callsGetAccountInformation() = runBlocking<Unit> {
        whenever(userManager.getAccountInfo()).thenReturn(AccountInformation())
        subject = Robolectric.setupActivity(AccountActivity::class.java)
        verify(userManager).getAccountInfo()
    }`

here -> usermanager.getAccountInfo() is a suspend function.

**Comment by nf17** [comment]
It was the mockito version, 2.10 and below does not support suspend functions. bumping it to latest(2.12) fixed it. Is the latest mockito-kotlin dependent on mockito version 2.8? i was not referencing mockito directly would doing so cause any issue?
