### ISSUE TITLE
Mockito eq on list to check argument is not working

### ISSUE THREAD

**Issue by jaumard** [nhaarman/mockito-kotlin#244]
Hello :)

I have the following test: 
```
package com.jaumard.data.media

import com.nhaarman.mockito_kotlin.eq
import com.nhaarman.mockito_kotlin.given
import com.nhaarman.mockito_kotlin.mock
import io.reactivex.Completable
import org.junit.runner.RunWith
import org.mockito.Mock
import org.mockito.junit.MockitoJUnitRunner

@RunWith(MockitoJUnitRunner::class)
class Test {

    @Mock
    lateinit var data:Data

    class Data {
        fun insert(data: List<Data>): Completable {
            return Completable.complete()
        }
    }

    @org.junit.Test
    fun test() {
        val list = ArrayList<Data>()
        val item1 = mock<Data>()
        list.add(item1)
        given(data.insert(eq(list))).willReturn(Completable.complete())
    }
}

```

The java equivalent is green but this one failed with: 

```
org.mockito.exceptions.misusing.WrongTypeOfReturnValue: 
CompletableEmpty cannot be returned by toString()
toString() should return String
***
If you're unsure why you're getting above error read on.
Due to the nature of the syntax above problem might occur because:
1. This exception *might* occur in wrongly written multi-threaded tests.
   Please refer to Mockito FAQ on limitations of concurrency testing.
2. A spy is stubbed using when(spy.foo()).then() syntax. It is safer to stub spies - 
   - with doReturn|Throw() family of methods. More in javadocs for Mockito.spy() method.


	at com.jaumard.data.media.Test.test(Test.kt:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:79)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:85)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)


Process finished with exit code 255

```

If I don't use `eq` but `anyList` instead then it work. Is there a bug or did I miss something ?

**Comment by jaumard** [comment]
Ok weird thing, it append to few other test also with RX Completable return type. If it return `Completable.defer {....}`  test is red but `Completable.fromCallable {` test is green

**Comment by bohsen** [comment]
To mock the data class you would have to open it up.

    open class Data {
        open fun insert(data: List<Data>): Completable {
            return Completable.complete()
        }
    }

    @Test
    fun mockOpenClass() {
        val data = mock<Data>()
        val actual = Completable.complete()
        whenever(data.insert(ArgumentMatchers.anyList())).thenReturn(actual)
        val expected = data.insert(listOf(Data()))
        MatcherAssert.assertThat(expected, Is.`is`(actual))
    }

**Comment by jaumard** [comment]
But I enabled the mockito feature to be able to mock final classes so I shouldn't have to open it, or all my classes of my project will be open just for testing and that's not what I want

**Comment by bohsen** [comment]
Then you should check that mockito inline mockmaker is correctly setup. I usually [come back to this article](https://antonioleiva.com/mockito-2-kotlin/) for the correct setup.

**Comment by bohsen** [comment]
Just checked. The test passes with inline mockmaker enabled.

**Comment by nhaarman** [comment]
Your test is successful on the `2.x` branch, so I assume whatever it was has been fixed.
