### ISSUE TITLE
Testing suspending function types fails when invocation is done in different context

### ISSUE THREAD

**Issue by matejdro** [nhaarman/mockito-kotlin#247]
Run this test code:

```kotlin
val suspendFunction : suspend () -> Unit = mock()

runBlocking {
    suspendFunction.invoke()
}

runBlocking {
    verify(suspendFunction).invoke()
}
```

It should succeed (function was invoked, so verify should pass), but it fails with an error:

```
Argument(s) are different! Wanted:
function1.invoke(
    (testLambda$2) Function2<kotlinx.coroutines.experimental.CoroutineScope, kotlin.coroutines.experimental.Continuation<? super kotlin.Unit>, java.lang.Object>
);
-> at LambdaTest$testLambda$2.doResume(TestTest.kt:19)
Actual invocation has different arguments:
function1.invoke(
    (testLambda$1) Function2<kotlinx.coroutines.experimental.CoroutineScope, kotlin.coroutines.experimental.Continuation<? super kotlin.Unit>, java.lang.Object>
);
```

Reproduced on versions:
```
ext.kotlin_version = '1.2.31'
compile "org.jetbrains.kotlinx:kotlinx-coroutines-android:0.22.5"
testCompile 'com.nhaarman.mockitokotlin2:mockito-kotlin:2.0.0-alpha03'
```

**Comment by matejdro** [comment]
I don't think "the right way to use coroutines" matters here.

`verify` is supposed to verify that method has been called, right? And in my example it HAS been called. So that check should succeed.

**Comment by matejdro** [comment]
Yes, I understand that. But mockito is supposed to verify if method is called, right? It shouldn't care on what context the method is called.

For example `verify()` always works for normal methods regardless of on what threads they are called.

Example in the first post is of course not real-world one. It is just shortest example I could make for bug report. In real world, need to verify method call from different context is not really that uncommon.

**Comment by flavioarfaria** [comment]
Maybe related to this: https://github.com/nhaarman/mockito-kotlin/issues/205

**Comment by miketrewartha** [comment]
I would agree with this, especially given the point about threads that @matejdro made and the fact that this library is written to make working with Mockito and Kotlin easier. Here's another example of this failing:

```kotlin
package com.example

import com.google.common.truth.Truth.assertThat
import com.nhaarman.mockitokotlin2.mock
import com.nhaarman.mockitokotlin2.verify
import com.nhaarman.mockitokotlin2.whenever
import kotlinx.coroutines.runBlocking
import org.spekframework.spek2.Spek
import org.spekframework.spek2.style.specification.describe

interface SomeInterface {
    suspend fun someSuspendFunction(): Boolean
}

class SuspendSpec : Spek({

    val mockInterface by memoized { mock<SomeInterface>() }

    describe("stubbing a suspend function") {

        beforeEachTest {
            runBlocking { whenever(mockInterface.someSuspendFunction()) }.thenReturn(true)
        }

        it("gives you the return value that you asked for") {
            val returnValue: Boolean? = runBlocking { mockInterface.someSuspendFunction() }
            assertThat(returnValue).isTrue()
        }

        it("lets you verify invocation of the stubbed function") {
            runBlocking { mockInterface.someSuspendFunction() }
            runBlocking { verify(mockInterface).someSuspendFunction() }
        }
    }
})
```

Both specs fail, but should pass IMO:
```
expected: true
but was : null
	at com.example.SuspendSpec$1$1$2.invoke(SuspendSpec.kt:27)
	at com.example.SuspendSpec$1$1$2.invoke(SuspendSpec.kt:15)
	at org.spekframework.spek2.runtime.scope.TestScopeImpl.execute(Scopes.kt:87)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:28)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:31)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:31)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:15)
	at org.spekframework.spek2.runtime.AbstractRuntime.execute(SpekRuntime.kt:32)
	at org.spekframework.spek2.junit.SpekTestEngine.execute(SpekTestEngine.kt:55)
	at [[Testing framework: 3 frames collapsed (https://goo.gl/aH3UyP)]].(:0)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:92)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$100(JUnitPlatformTestClassProcessor.java:77)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:73)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at [[Reflective call: 4 frames collapsed (https://goo.gl/aH3UyP)]].(:0)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:131)
	at [[Reflective call: 4 frames collapsed (https://goo.gl/aH3UyP)]].(:0)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
```
```
Argument(s) are different! Wanted:
someInterface.someSuspendFunction(
    Continuation @ com.example.SuspendSpec$1$1$3$2
);
-> at com.example.SuspendSpec$1$1$3$2.invokeSuspend(SuspendSpec.kt:32)
Actual invocation has different arguments:
someInterface.someSuspendFunction(
    Continuation @ com.example.SuspendSpec$1$1$3$1
);
-> at com.example.SuspendSpec$1$1$3$1.invokeSuspend(SuspendSpec.kt:31)

	at com.example.SuspendSpec$1$1$3$2.invokeSuspend(SuspendSpec.kt:32)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask$DefaultImpls.run(Dispatched.kt:147)
	at kotlinx.coroutines.DispatchedContinuation.run(Dispatched.kt:14)
	at kotlinx.coroutines.EventLoopBase.processNextEvent(EventLoop.kt:136)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:133)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:52)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:41)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.example.SuspendSpec$1$1$3.invoke(SuspendSpec.kt:32)
	at com.example.SuspendSpec$1$1$3.invoke(SuspendSpec.kt:15)
	at org.spekframework.spek2.runtime.scope.TestScopeImpl.execute(Scopes.kt:87)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:28)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:31)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:31)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:15)
	at org.spekframework.spek2.runtime.AbstractRuntime.execute(SpekRuntime.kt:32)
	at org.spekframework.spek2.junit.SpekTestEngine.execute(SpekTestEngine.kt:55)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:92)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$100(JUnitPlatformTestClassProcessor.java:77)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:73)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by bohsen** [comment]
This is not a bug in Mockito-kotlin. I still believe it comes down to how coroutines work.

Suspending functions are not some special type of functions. They are regular functions that use CPS transformation to add an extra parameter of type `[Continuation]`(https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.coroutines.experimental/-continuation/index.html) (a classical generic callback). Have a look at [this](https://www.youtube.com/watch?v=YrrUCSi72E8&t=8s).

So for each invocation of `runBlocking { ... }` you have different `Continuation`'s passed into your function.

The stacktrace actually tells you this.

```
Argument(s) are different! Wanted:
someInterface.someSuspendFunction(
    Continuation @ com.example.SuspendSpec$1$1$3$2
);
-> at com.example.SuspendSpec$1$1$3$2.invokeSuspend(SuspendSpec.kt:32)
Actual invocation has different arguments:
someInterface.someSuspendFunction(
    Continuation @ com.example.SuspendSpec$1$1$3$1
```

So just to recap. I don't believe this is an issue for mockito-kotlin to handle, but should be discussed in the coroutine project. Though I actually don't believe there would ever exist an use-case for this, as to me it wouldn't ever make sense to call `runBlocking` twice in the same context.

**Comment by matejdro** [comment]
> I don't believe this is an issue for mockito-kotlin to handle, but should be discussed in the coroutine project

I'm not sure coroutines people can change anything, this is how they made their system. If anything, it should be discussed within regular mockito project. But mockito is java-only and does not really involve kotlin, so next best thing is this project.

I propose solution that somehow ignores first argument here (or automatically marks it as `any()` somehow). But I do not know enough of mockito's internals to be any more practical.

> as to me it wouldn't ever make sense to call runBlocking twice in the same context

As already stated before, example in the first post is NOT production example. I agree it is completely useless. But at the same time, it is the most simple example one can make for a bug report.

**Comment by miketrewartha** [comment]
We can debate what to call this ("bug" or "not a bug") all we want, but it doesn't really matter. The important thing is that we're looking for a way to mock and verify suspend functions. Given that suspend functions are a Kotlin concept, and we're trying to mock/verify them, a Mockito concept, it seems rather fitting that mockito-kotlin provide a way to do this.

**Comment by bohsen** [comment]
@miketrewartha There is - take a look at [the tests in the source code](https://github.com/nhaarman/mockito-kotlin/blob/2.x/mockito-kotlin/src/test/kotlin/test/CoroutinesTest.kt).

**Comment by miketrewartha** [comment]
@bohsen all of those make sense, but I'm looking for a way to mock a suspend function for a mock I created further up in a test (in some contextual setup), because I don't want to have to redefine everything inside each test or before block:

```
object SubjectClassSpec : Spek({
    val mockDependency by memoized { mock<DependencyClass>() }
    val subject by memoized { SubjectClass(mockDependency) }

    describe("doing something") {
        beforeEachTest {
            // This doesn't work (not calling someSuspendFunction in a suspend function or coroutine), 
            // so how can I mock this function without having to redefine my subject and mockDependency
            // in this specific beforeEachTest block?
            whenever(mockDependency.someSuspendFunction()).thenReturn("some value")
        }
        // ... some actual assertions in `it` blocks
    }
})
```

**Comment by miketrewartha** [comment]
Here's another example of something related that I'm stuck on:
```kotlin
object SubjectClassSpec : Spek({

    val mockDependency by memoized { mock<DependencyClass>() }
    val subject by memoized { SubjectClass(mockDependency) }

    describe("doing something") {
        val result = subject.doSomethingThatCallsTheDependencySuspendFunction()

        it("uses the dependency in a certain way") {
            runBlocking { verify(mockDependency).someSuspendFunction() }
        }
    }
})
```
This results in a test failure because the continuations aren't the same. Now that I think about is, I'm wondering if that's a problem that's specific to my setup. I have a class that follows the same general pattern as above and in my actual function (represented by `doSomethingThatCallsTheDependencySuspendFunction()` here), I have a `runBlocking { ... }` that wraps the suspend function's call. Unfortunately, the function that calls the suspend function is part of a Java interface, so I can't mark it as a `suspend` function.

**Comment by bohsen** [comment]
Should work even with a Java interface I believe. Try wrapping 
`val result = subject.doSomethingThatCallsTheDependencySuspendFunction()` with `runBlocking {}``

Like this (not using Java interface though, but shouldn't matter):

```kotlin
object SpekTestCoroutines : Spek({

    val mockDependency by memoized { mock<Foo>() }
    val subject by memoized { Bar(mockDependency) }

    describe("doing something") {
        runBlocking {
            subject.result(42)

            it("uses the dependency in a certain way") {
                runBlocking { verify(mockDependency).suspending() }
            }
        }
    }
})

interface Foo {
    suspend fun suspending(): Int
    fun nonsuspending(): Int
}

class Bar(val foo: Foo) {
    suspend fun result(r: Int) = withContext(CommonPool) { foo.suspending() }
}
```

This is using spek 2.0.0-alpha.2. Here's a section of my build.gradle:

```gradle
dependencies {
    ...
    testCompile 'org.junit.jupiter:junit-jupiter-api:5.2.0'

    testImplementation ('org.spekframework.spek2:spek-dsl-jvm:2.0.0-alpha.2')  {
        exclude group: 'org.jetbrains.kotlin'
    }
    testRuntimeOnly ('org.spekframework.spek2:spek-runner-junit5:2.0.0-alpha.2') {
        exclude group: 'org.junit.platform'
        exclude group: 'org.jetbrains.kotlin'
    }

    // spek requires kotlin-reflect, can be omitted if already in the classpath
    testRuntimeOnly "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
}

// setup the test task
test {
    useJUnitPlatform {
        includeEngines 'spek2'
    }
}
```

**Comment by matejdro** [comment]
Still broken for me with `com.nhaarman.mockitokotlin2:mockito-kotlin:2.1.0`, `Kotlin 1.3.20` and `coroutines-android 1.1.1`

**Comment by mochadwi** [comment]
Is this still broken? @matejdro

**Comment by matejdro** [comment]
Sorry, I'm not using mockito-kotlin anymore so I cannot confirm.

**Comment by kyodgorbek** [comment]
Guys I also getting the same  problem https://stackoverflow.com/questions/68113141/exception-in-thread-main-coroutine2-java-lang-nullpointerexception?noredirect=1#comment120385629_68113141

**Comment by danielesegato** [comment]
I'm also experienced this in mockito-kotlin `3.2.0`.

I've an interface
```kotlin
interface Example {
  val onSubmit: suspend () -> Unit
}
```

I need to mock this interface

```kotlin
val mockedOnSubmit = mock<suspend () -> Unit>()
val mockedExample = mock<Example> {
  on { onSubmit } doReturn mockedOnSubmit
}
```
the verify on `mockedOnSubmit` fails complaining the continuation is different.

```kotlin
verify(mockedOnSubmit, times(1)).invoke()
```

Any input on how to test in this situation? I really don't care the continuation is different, of course it is. I just want to check it is invoked.

**Comment by kyodgorbek** [comment]
Hi did you used
https://proandroiddev.com/how-to-unit-test-code-with-coroutines-50c1640f6bef
kotlin coroutines test?

**Comment by danielesegato** [comment]
@kyodgorbek what is it that you are asking me if I used in that article?

I didn't use that article. But I do have my own TestCoroutineDispatcher rule.

Can you elaborate on what you think is the cause?

By the way... if I change

```kotlin
interface Example {
  val onSubmit: suspend () -> Unit
}
```
to
```kotlin
interface Example {
  suspend fun onSubmit()
}
```

it is mockable and works like I expect, so I'm not sure why the lambda wouldn't
