### ISSUE TITLE
Confusing assertion errors when verifying

### ISSUE THREAD

**Issue by crypticmind** [nhaarman/mockito-kotlin#288]
### Versions
- mockito-kotlin: `2.0.0-RC2`
- mockito: `2.15.0`
- Kotlin: `1.2.51`

### Issue
I see assertion errors even for correct tests that pass, against working code.

### Detail
Let's say I have this test:

```kotlin
import com.nhaarman.mockitokotlin2.*
import org.assertj.core.api.Assertions.assertThat
import org.junit.Test
import java.util.concurrent.atomic.AtomicInteger

class Verifications {

    interface UnderTest {
        fun f(s: String, i: AtomicInteger): String
    }

    @Test
    fun verifications() {

        val underTest = mock<UnderTest>()

        underTest.f("s1", AtomicInteger(1))

        underTest.f("s2", AtomicInteger(2))

        verify(underTest).f(
            check { assertThat(it).isEqualTo("s1") },
            check { assertThat(it.get()).isEqualTo(1) })

        verify(underTest).f(
            check { assertThat(it).isEqualTo("s2") },
            check { assertThat(it.get()).isEqualTo(2) })

    }
}
```

When I run this, it passes. If I change the values being checked in the `verify` calls, it fails the test as expected. Also if I verify more than one `times` of a call it fails, again, as expected.

However, I noticed that apparently mockito-kotlin, when `verify`ing, it tries all invocations to see if there is one for which all checks pass in order to mark that verification as succeeded. The issue is that while trying the other invocations it will spit out assertion errors that are then ignored after a successfully verified invocation. The test succeeds, but I see this output:

```
org.junit.ComparisonFailure: expected:<"s[1]"> but was:<"s[2]">
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at Verifications$verifications$1.invoke(Verifications.kt:23)
    at Verifications$verifications$1.invoke(Verifications.kt:7)
    at Verifications$verifications$$inlined$check$1.matches(Verification.kt:246)
    at org.mockito.internal.invocation.TypeSafeMatching.apply(TypeSafeMatching.java:24)
    at org.mockito.internal.invocation.MatcherApplicationStrategy.forEachMatcherAndArgument(MatcherApplicationStrategy.java:82)
    at org.mockito.internal.invocation.InvocationMatcher.argumentsMatch(InvocationMatcher.java:152)
    at org.mockito.internal.invocation.InvocationMatcher.matches(InvocationMatcher.java:81)
    at org.mockito.internal.invocation.InvocationsFinder$RemoveNotMatching.isOut(InvocationsFinder.java:149)
    at org.mockito.internal.invocation.InvocationsFinder$RemoveNotMatching.isOut(InvocationsFinder.java:141)
    at org.mockito.internal.util.collections.ListUtil.filter(ListUtil.java:22)
    at org.mockito.internal.invocation.InvocationsFinder.findInvocations(InvocationsFinder.java:24)
    at org.mockito.internal.verification.checkers.MissingInvocationChecker.checkMissingInvocation(MissingInvocationChecker.java:30)
    at org.mockito.internal.verification.Times.verify(Times.java:37)
    at org.mockito.internal.verification.MockAwareVerificationMode.verify(MockAwareVerificationMode.java:27)
    at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:75)
    at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
    at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:35)
    at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:65)
    at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:51)
    at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptAbstract(MockMethodInterceptor.java:153)
    at Verifications$UnderTest$MockitoMock$257558211.f(Unknown Source)
    at Verifications.verifications(Verifications.kt:22)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
org.junit.ComparisonFailure: expected:<"s[1]"> but was:<"s[2]">
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at Verifications$verifications$1.invoke(Verifications.kt:23)
    at Verifications$verifications$1.invoke(Verifications.kt:7)
    at Verifications$verifications$$inlined$check$1.matches(Verification.kt:246)
    at org.mockito.internal.invocation.TypeSafeMatching.apply(TypeSafeMatching.java:24)
    at org.mockito.internal.invocation.MatcherApplicationStrategy.forEachMatcherAndArgument(MatcherApplicationStrategy.java:82)
    at org.mockito.internal.invocation.InvocationMatcher.argumentsMatch(InvocationMatcher.java:152)
    at org.mockito.internal.invocation.InvocationMatcher.matches(InvocationMatcher.java:81)
    at org.mockito.internal.invocation.InvocationsFinder$RemoveNotMatching.isOut(InvocationsFinder.java:149)
    at org.mockito.internal.invocation.InvocationsFinder$RemoveNotMatching.isOut(InvocationsFinder.java:141)
    at org.mockito.internal.util.collections.ListUtil.filter(ListUtil.java:22)
    at org.mockito.internal.invocation.InvocationsFinder.findInvocations(InvocationsFinder.java:24)
    at org.mockito.internal.verification.checkers.NumberOfInvocationsChecker.checkNumberOfInvocations(NumberOfInvocationsChecker.java:33)
    at org.mockito.internal.verification.Times.verify(Times.java:39)
    at org.mockito.internal.verification.MockAwareVerificationMode.verify(MockAwareVerificationMode.java:27)
    at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:75)
    at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
    at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:35)
    at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:65)
    at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:51)
    at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptAbstract(MockMethodInterceptor.java:153)
    at Verifications$UnderTest$MockitoMock$257558211.f(Unknown Source)
    at Verifications.verifications(Verifications.kt:22)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
org.junit.ComparisonFailure: expected:<"s[2]"> but was:<"s[1]">
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at Verifications$verifications$3.invoke(Verifications.kt:27)
    at Verifications$verifications$3.invoke(Verifications.kt:7)
    at Verifications$verifications$$inlined$check$3.matches(Verification.kt:246)
    at org.mockito.internal.invocation.TypeSafeMatching.apply(TypeSafeMatching.java:24)
    at org.mockito.internal.invocation.MatcherApplicationStrategy.forEachMatcherAndArgument(MatcherApplicationStrategy.java:82)
    at org.mockito.internal.invocation.InvocationMatcher.argumentsMatch(InvocationMatcher.java:152)
    at org.mockito.internal.invocation.InvocationMatcher.matches(InvocationMatcher.java:81)
    at org.mockito.internal.invocation.InvocationsFinder$RemoveNotMatching.isOut(InvocationsFinder.java:149)
    at org.mockito.internal.invocation.InvocationsFinder$RemoveNotMatching.isOut(InvocationsFinder.java:141)
    at org.mockito.internal.util.collections.ListUtil.filter(ListUtil.java:22)
    at org.mockito.internal.invocation.InvocationsFinder.findInvocations(InvocationsFinder.java:24)
    at org.mockito.internal.verification.checkers.MissingInvocationChecker.checkMissingInvocation(MissingInvocationChecker.java:30)
    at org.mockito.internal.verification.Times.verify(Times.java:37)
    at org.mockito.internal.verification.MockAwareVerificationMode.verify(MockAwareVerificationMode.java:27)
    at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:75)
    at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
    at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:35)
    at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:65)
    at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:51)
    at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptAbstract(MockMethodInterceptor.java:153)
    at Verifications$UnderTest$MockitoMock$257558211.f(Unknown Source)
    at Verifications.verifications(Verifications.kt:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
org.junit.ComparisonFailure: expected:<"s[2]"> but was:<"s[1]">
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at Verifications$verifications$3.invoke(Verifications.kt:27)
    at Verifications$verifications$3.invoke(Verifications.kt:7)
    at Verifications$verifications$$inlined$check$3.matches(Verification.kt:246)
    at org.mockito.internal.invocation.TypeSafeMatching.apply(TypeSafeMatching.java:24)
    at org.mockito.internal.invocation.MatcherApplicationStrategy.forEachMatcherAndArgument(MatcherApplicationStrategy.java:82)
    at org.mockito.internal.invocation.InvocationMatcher.argumentsMatch(InvocationMatcher.java:152)
    at org.mockito.internal.invocation.InvocationMatcher.matches(InvocationMatcher.java:81)
    at org.mockito.internal.invocation.InvocationsFinder$RemoveNotMatching.isOut(InvocationsFinder.java:149)
    at org.mockito.internal.invocation.InvocationsFinder$RemoveNotMatching.isOut(InvocationsFinder.java:141)
    at org.mockito.internal.util.collections.ListUtil.filter(ListUtil.java:22)
    at org.mockito.internal.invocation.InvocationsFinder.findInvocations(InvocationsFinder.java:24)
    at org.mockito.internal.verification.checkers.NumberOfInvocationsChecker.checkNumberOfInvocations(NumberOfInvocationsChecker.java:33)
    at org.mockito.internal.verification.Times.verify(Times.java:39)
    at org.mockito.internal.verification.MockAwareVerificationMode.verify(MockAwareVerificationMode.java:27)
    at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:75)
    at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
    at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:35)
    at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:65)
    at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:51)
    at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptAbstract(MockMethodInterceptor.java:153)
    at Verifications$UnderTest$MockitoMock$257558211.f(Unknown Source)
    at Verifications.verifications(Verifications.kt:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

Process finished with exit code 0
```

I would expect those messages to be suppressed, unless no matching call is found at all.

---

### Bonus question:

If I change the `i` parameter to `Int`, like this:
```kotlin
import com.nhaarman.mockitokotlin2.*
import org.assertj.core.api.Assertions.assertThat
import org.junit.Test

class Verifications {

    interface UnderTest {
        fun f(s: String, i: Int): String
    }

    @Test
    fun verifications() {

        val underTest = mock<UnderTest>()

        underTest.f("s1", 1)

        underTest.f("s2", 2)

        verify(underTest).f(
            check { assertThat(it).isEqualTo("s1") },
            check { assertThat(it).isEqualTo(1) })

        verify(underTest).f(
            check { assertThat(it).isEqualTo("s2") },
            check { assertThat(it).isEqualTo(2) })

    }
}
```

Then I get a `NullPointerException`:
```
java.lang.NullPointerException
    at Verifications.verifications(Verifications.kt:62)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code 255
```

How can I work around this problem?

**Comment by bohsen** [comment]
It's not clear from the docs but check() and stubs aren't best friends, when (like the case here) multiple invocations are performed. Your tests will pass, but they throw AssertionErrors. The workaround is to use argThat or argForWhich instead (take a look at [the source for check()](https://github.com/nhaarman/mockito-kotlin/blob/e59d36b4411f586b97e7b8937efd0041c69a8e9e/mockito-kotlin/src/main/kotlin/com/nhaarman/mockitokotlin2/Verification.kt#L235)):

```kotlin
interface UnderTest {
    fun f(s: String, i: AtomicInteger): String
}

@Test
fun verifications_with_argThat() {

    val underTest = mock<UnderTest>().apply {
        f("s1", AtomicInteger(1))
        f("s2", AtomicInteger(2))

        verify(this).f(
              argThat { equals("s1") },
              argThat { get().equals(1) })

        verify(this).f(
              argThat { equals("s2") },
              argThat { get().equals(2) })
    }
}
```

If you only had one invocation on your mock you wouldn't have had assertion errors. Like this:

```kotlin
@Test
fun verifications_with_check() {

    val underTest = mock<UnderTest>().apply {
        f("s1", AtomicInteger(1))

        verify(this).f(
              check {
                  assertThat(it, `is`("s1"))
              },
              check {
                  assertThat(it.get(), `is`(1))
              })
         }
     }
}
```

**Comment by crypticmind** [comment]
OK, I guess changing the implementation of `check` is not as easy as I thought. What about the NPE question?

**Comment by bohsen** [comment]
Just use Mockito.eq():

```kotlin
@Test
fun verifications() {

    val underTest = mock<UnderTest>()

    underTest.f("s1", 1)
    underTest.f("s2", 2)

    verify(underTest).f(eq("s1"), eq(1))
    verify(underTest).f(eq("s2"), eq(2))
}
```

**Comment by crypticmind** [comment]
Thank you for your help, @bohsen!
