### ISSUE TITLE
[Feature request] Support unsigned numbers

### ISSUE THREAD

**Issue by neworld** [nhaarman/mockito-kotlin#363]
Info:
- Reference: https://kotlinlang.org/docs/reference/basic-types.html#unsigned-integers
- KEEP: https://github.com/Kotlin/KEEP/blob/master/proposals/unsigned-types.md

Test case:
```
    @Test
    fun mockitoTest() {
        val fixture: UnsignedFixture = mock()

        fixture.ubyte(42u)
        fixture.ushort(42u)
        fixture.uInt(42u)
        fixture.uLong(42u)

        verify(fixture).ubyte(eq(42u))
        verify(fixture).ushort(eq(42u))
        verify(fixture).uInt(eq(42u))
        verify(fixture).uLong(eq(42u))
    }

    interface UnsignedFixture {
        fun ubyte(value: UByte)
        fun ushort(value: UShort)
        fun uInt(value: UInt)
        fun uLong(value: ULong)
    }
```

Error:
```
Argument(s) are different! Wanted:
unsignedFixture.uInt-WZ4Q5Ns((UInt) 42);
-> at lt.libredrop.peerdiscovery.PeerDiscoverySpecsComplainTest.mockitoTest(PeerDiscoverySpecsComplainTest.kt:72)
Actual invocations have different arguments:
unsignedFixture.uInt-WZ4Q5Ns((Integer) 42);
-> at lt.libredrop.peerdiscovery.PeerDiscoverySpecsComplainTest.mockitoTest(PeerDiscoverySpecsComplainTest.kt:67)
```

**Comment by bohsen** [comment]
Duplicate of #309 

@neworld The issue mentions a workaround, but not sure it fits your needs. Also as long as Mockito-kotlin depends on mockito (java) internally I don't think there's an easy solution to this.
